apiVersion: v1
kind: ReplicationController
metadata:
    name: server
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: server
        spec:
            containers:
                - name: gentoo-orca-server
              image: pallavagarwal07/gentoo-stabilization:server
              imagePullPolicy: Always
              ports:
                  - containerPort: 80
              volumeMounts:
                  - name: shared-folder
                    mountPath: /data
            - name: gentoo-orca-flag-solver
              image: pallavagarwal07/gentoo-stabilization:solver
              command: [ "python2", "/root/discovery.py" ]
              ports:
                  - containerPort: 7071
            - name: gentoo-orca-dep-solver
              image: pallavagarwal07/gentoo-stabilization:solver
              imagePullPolicy: Always
              command: [ "python2", "/root/dependency.py" ]
              ports:
                  - containerPort: 7072
            volumes:
            - name: shared-folder
              hostPath:
                path: /home/ubuntu/shared
